// packages/react/src/components/FloatingDelayGroup.tsx
import * as React from 'react';
import {useModernLayoutEffect} from '@floating-ui/react/utils';

import {getDelay} from '../hooks/useHover';
import type {FloatingRootContext} from '../types';

type Delay = number | Partial<{open: number; close: number}>;

interface GroupState {
  delay: Delay;
  initialDelay: Delay;
  currentId: any;
  timeoutMs: number;
  isInstantPhase: boolean;
}

interface GroupContext extends GroupState {
  setCurrentId: React.Dispatch<React.SetStateAction<any>>;
  setState: React.Dispatch<Partial<GroupState>>;
}

const NOOP = () => {};

const FloatingDelayGroupContext = React.createContext<
  GroupState & {
    setCurrentId: (currentId: any) => void;
    setState: React.Dispatch<Partial<GroupState>>;
  }
>({
  delay: 0,
  initialDelay: 0,
  timeoutMs: 0,
  currentId: null,
  setCurrentId: NOOP,
  setState: NOOP,
  isInstantPhase: false,
});

/**
 * @deprecated
 * Use the return value of `useDelayGroup()` instead.
 */
export const useDelayGroupContext = (): GroupContext =>
  React.useContext(FloatingDelayGroupContext);

export interface FloatingDelayGroupProps {
  children?: React.ReactNode;
  /**
   * The delay to use for the group.
   */
  delay: Delay;
  /**
   * An optional explicit timeout to use for the group, which represents when
   * grouping logic will no longer be active after the close delay completes.
   * This is useful if you want grouping to “last” longer than the close delay,
   * for example if there is no close delay at all.
   */
  timeoutMs?: number;
}

/**
 * Provides context for a group of floating elements that should share a
 * `delay`.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 */
export function FloatingDelayGroup(
  props: FloatingDelayGroupProps,
): React.JSX.Element {
  const {children, delay, timeoutMs = 0} = props;

  const [state, setState] = React.useReducer(
    (prev: GroupState, next: Partial<GroupState>): GroupState => ({
      ...prev,
      ...next,
    }),
    {
      delay,
      timeoutMs,
      initialDelay: delay,
      currentId: null,
      isInstantPhase: false,
    },
  );

  const initialCurrentIdRef = React.useRef<any>(null);

  const setCurrentId = React.useCallback((currentId: any) => {
    setState({currentId});
  }, []);

  useModernLayoutEffect(() => {
    if (state.currentId) {
      if (initialCurrentIdRef.current === null) {
        initialCurrentIdRef.current = state.currentId;
      } else if (!state.isInstantPhase) {
        setState({isInstantPhase: true});
      }
    } else {
      if (state.isInstantPhase) {
        setState({isInstantPhase: false});
      }
      initialCurrentIdRef.current = null;
    }
  }, [state.currentId, state.isInstantPhase]);

  return (
    <FloatingDelayGroupContext.Provider
      value={React.useMemo(
        () => ({...state, setState, setCurrentId}),
        [state, setCurrentId],
      )}
    >
      {children}
    </FloatingDelayGroupContext.Provider>
  );
}

interface UseGroupOptions {
  /**
   * Whether delay grouping should be enabled.
   * @default true
   */
  enabled?: boolean;
  id?: any;
}

/**
 * Enables grouping when called inside a component that's a child of a
 * `FloatingDelayGroup`.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 */
export function useDelayGroup(
  context: FloatingRootContext,
  options: UseGroupOptions = {},
): GroupContext {
  const {open, onOpenChange, floatingId} = context;
  const {id: optionId, enabled = true} = options;
  const id = optionId ?? floatingId;

  const groupContext = useDelayGroupContext();
  const {currentId, setCurrentId, initialDelay, setState, timeoutMs} =
    groupContext;

  useModernLayoutEffect(() => {
    if (!enabled) return;
    if (!currentId) return;

    setState({
      delay: {
        open: 1,
        close: getDelay(initialDelay, 'close'),
      },
    });

    if (currentId !== id) {
      onOpenChange(false);
    }
  }, [enabled, id, onOpenChange, setState, currentId, initialDelay]);

  useModernLayoutEffect(() => {
    function unset() {
      console.log('unset');
      onOpenChange(false);
      setState({delay: initialDelay, currentId: null});
    }    

    if (!enabled) return;
    if (!currentId) return;

    console.log('open', open);
    console.log('enabled', enabled);
    console.log('group.currentId', currentId);
    console.log('id', id);

    if (!open && currentId === id) {
      if (timeoutMs) {
        const timeout = window.setTimeout(unset, timeoutMs);
        return () => {
          clearTimeout(timeout);
        };
      }

      unset();
    }
  }, [
    enabled,
    open,
    setState,
    currentId,
    id,
    onOpenChange,
    initialDelay,
    timeoutMs,
  ]);

  useModernLayoutEffect(() => {
    if (!enabled) return;
    if (setCurrentId === NOOP || !open) return;
    console.log('setting currentId', id);
    setCurrentId(id);
  }, [enabled, open, setCurrentId, id]);

  return groupContext;
}

// packages/solid/src/components/FloatingDelayGroup.tsx
// FloatingDelayGroup.solid.tsx
/* eslint-disable solid/reactivity */
import {
  Accessor,
  JSX,
  JSXElement,
  createContext,
  createEffect,
  mergeProps,
  onCleanup,
  useContext,
} from 'solid-js';
import { createStore } from 'solid-js/store';

import { getDelay } from '../hooks/useHover';
import type { FloatingContext } from '../types';

type Delay = number | Partial<{ open: number; close: number }>;

interface GroupState {
  delay: Delay;
  initialDelay: Delay;
  currentId: any;
  timeoutMs: number;
  isInstantPhase: boolean;
}

interface GroupContext extends GroupState {
  setState: (partial: Partial<GroupState>) => void;
  setCurrentId: (id: any) => void;
}

const FloatingDelayGroupContext = createContext<GroupContext>({
  delay: 0,
  initialDelay: 0,
  currentId: null,
  timeoutMs: 0,
  isInstantPhase: false,
  setState: () => undefined,
  setCurrentId: () => undefined,
});

export const useDelayGroupContext = () => useContext(FloatingDelayGroupContext);

export interface FloatingDelayGroupProps {
  children?: JSXElement;
  delay: Delay;
  timeoutMs?: number;
}

/**
 * Provides context for a group of floating elements that should share a
 * `delay`.
 */
export const FloatingDelayGroup = (
  props: FloatingDelayGroupProps
): JSX.Element => {
  const [state, setState] = createStore<GroupState>({
    delay: props.delay,
    initialDelay: props.delay,
    currentId: null,
    timeoutMs: props.timeoutMs ?? 0,
    isInstantPhase: false,
  });

  let initialCurrentIdRef: any = null;

  const setCurrentId = (id: any) => {
    setState({ currentId: id });
  };

  // Mirror React’s useModernLayoutEffect for tracking `isInstantPhase` & `currentId`
  createEffect(() => {
    const { currentId, isInstantPhase } = state;

    if (currentId) {
      if (initialCurrentIdRef === null) {
        initialCurrentIdRef = currentId;
      } else if (!isInstantPhase) {
        setState({ isInstantPhase: true });
      }
    } else {
      if (isInstantPhase) {
        setState({ isInstantPhase: false });
      }
      initialCurrentIdRef = null;
    }
  });

  // Build a stable context object (including both setState and setCurrentId)
  const context = mergeProps({ setState, setCurrentId }, state);

  return (
    <FloatingDelayGroupContext.Provider value={context}>
      {props.children}
    </FloatingDelayGroupContext.Provider>
  );
};

interface UseGroupOptions {
  id: any;
}

/**
 * Enables grouping when called inside a component that's a child of a
 * `FloatingDelayGroup`.
 */
export const useDelayGroup = (
  floatingContext: Accessor<FloatingContext>,
  props: UseGroupOptions
) => {
  const group = useDelayGroupContext();

  // 1) When `currentId` changes, update delays and close anything that isn’t this `id`.
  createEffect(() => {
    if (group.currentId) {
      // Update delay immediately
      group.setState({
        delay: {
          open: 1,
          close: getDelay(group.initialDelay, 'close'),
        },
      });

      if (group.currentId !== props.id) {
        floatingContext().onOpenChange(false);
      }
    }
  });

  // 2) When this item closes but it was the `currentId`, start the timeout/unset logic.
  createEffect(() => {
    if (!floatingContext().open() && group.currentId === props.id) {
      const unset = () => {
        floatingContext().onOpenChange(false);
        group.setState({ delay: group.initialDelay, currentId: null });
      };

      console.log('timeoutMs', group.timeoutMs)

      if (group.timeoutMs) {
        const t = window.setTimeout(unset, group.timeoutMs);
        onCleanup(() => {
          clearTimeout(t);
        });
      } else {
        unset();
      }
    }
  });

  // 3) Whenever this item opens, set `currentId = props.id`. Whenever it closes, clear it.
  createEffect(() => {
    if (floatingContext().open()) {
      group.setCurrentId(props.id);
    } else {
      // If it’s closing, don’t immediately clear `currentId` here—
      // the “close” effect above will do that (after timeout).
      // However, React version does set `currentId = null` immediately on close only if no timeoutMs.
      if (!group.timeoutMs) {
        group.setCurrentId(null);
      }
    }
  });

  return group;
};
