// packages/react/src/hooks/useHover.ts
import * as React from 'react';
import {isElement} from '@floating-ui/utils/dom';
import {
  contains,
  getDocument,
  isMouseLikePointerType,
  useLatestRef,
  useEffectEvent,
  useModernLayoutEffect,
} from '@floating-ui/react/utils';

import {
  useFloatingParentNodeId,
  useFloatingTree,
} from '../components/FloatingTree';
import type {
  Delay,
  ElementProps,
  FloatingContext,
  FloatingRootContext,
  FloatingTreeType,
  OpenChangeReason,
  SafePolygonOptions,
} from '../types';
import {createAttribute} from '../utils/createAttribute';
import {clearTimeoutIfSet} from '../utils/clearTimeoutIfSet';

const safePolygonIdentifier = createAttribute('safe-polygon');

export interface HandleCloseContext extends FloatingContext {
  onClose: () => void;
  tree?: FloatingTreeType | null;
  leave?: boolean;
}

export interface HandleClose {
  (context: HandleCloseContext): (event: MouseEvent) => void;
  __options?: SafePolygonOptions;
}

export function getDelay(
  value: UseHoverProps['delay'],
  prop: 'open' | 'close',
  pointerType?: PointerEvent['pointerType'],
) {
  if (pointerType && !isMouseLikePointerType(pointerType)) {
    return 0;
  }

  if (typeof value === 'number') {
    return value;
  }

  if (typeof value === 'function') {
    const result = value();
    if (typeof result === 'number') {
      return result;
    }
    return result?.[prop];
  }

  return value?.[prop];
}

function getRestMs(value: number | (() => number)) {
  if (typeof value === 'function') {
    return value();
  }
  return value;
}

export interface UseHoverProps {
  /**
   * Whether the Hook is enabled, including all internal Effects and event
   * handlers.
   * @default true
   */
  enabled?: boolean;
  /**
   * Accepts an event handler that runs on `mousemove` to control when the
   * floating element closes once the cursor leaves the reference element.
   * @default null
   */
  handleClose?: HandleClose | null;
  /**
   * Waits until the user’s cursor is at “rest” over the reference element
   * before changing the `open` state.
   * @default 0
   */
  restMs?: number | (() => number);
  /**
   * Waits for the specified time when the event listener runs before changing
   * the `open` state.
   * @default 0
   */
  delay?: Delay | (() => Delay);
  /**
   * Whether the logic only runs for mouse input, ignoring touch input.
   * Note: due to a bug with Linux Chrome, "pen" inputs are considered "mouse".
   * @default false
   */
  mouseOnly?: boolean;
  /**
   * Whether moving the cursor over the floating element will open it, without a
   * regular hover event required.
   * @default true
   */
  move?: boolean;
}

/**
 * Opens the floating element while hovering over the reference element, like
 * CSS `:hover`.
 * @see https://floating-ui.com/docs/useHover
 */
export function useHover(
  context: FloatingRootContext,
  props: UseHoverProps = {},
): ElementProps {
  const {open, onOpenChange, dataRef, events, elements} = context;
  const {
    enabled = true,
    delay = 0,
    handleClose = null,
    mouseOnly = false,
    restMs = 0,
    move = true,
  } = props;

  const tree = useFloatingTree();
  const parentId = useFloatingParentNodeId();
  const handleCloseRef = useLatestRef(handleClose);
  const delayRef = useLatestRef(delay);
  const openRef = useLatestRef(open);
  const restMsRef = useLatestRef(restMs);

  const pointerTypeRef = React.useRef<string>();
  const timeoutRef = React.useRef(-1);
  const handlerRef = React.useRef<(event: MouseEvent) => void>();
  const restTimeoutRef = React.useRef(-1);
  const blockMouseMoveRef = React.useRef(true);
  const performedPointerEventsMutationRef = React.useRef(false);
  const unbindMouseMoveRef = React.useRef(() => {});
  const restTimeoutPendingRef = React.useRef(false);

  const isHoverOpen = useEffectEvent(() => {
    const type = dataRef.current.openEvent?.type;
    return type?.includes('mouse') && type !== 'mousedown';
  });

  // When closing before opening, clear the delay timeouts to cancel it
  // from showing.
  React.useEffect(() => {
    if (!enabled) return;

    function onOpenChange({open}: {open: boolean}) {
      if (!open) {
        clearTimeoutIfSet(timeoutRef);
        clearTimeoutIfSet(restTimeoutRef);
        blockMouseMoveRef.current = true;
        restTimeoutPendingRef.current = false;
      }
    }

    events.on('openchange', onOpenChange);
    return () => {
      events.off('openchange', onOpenChange);
    };
  }, [enabled, events]);

  React.useEffect(() => {
    if (!enabled) return;
    if (!handleCloseRef.current) return;
    if (!open) return;

    function onLeave(event: MouseEvent) {
      if (isHoverOpen()) {
        onOpenChange(false, event, 'hover');
      }
    }

    const html = getDocument(elements.floating).documentElement;
    html.addEventListener('mouseleave', onLeave);
    return () => {
      html.removeEventListener('mouseleave', onLeave);
    };
  }, [
    elements.floating,
    open,
    onOpenChange,
    enabled,
    handleCloseRef,
    isHoverOpen,
  ]);

  const closeWithDelay = React.useCallback(
    (
      event: Event,
      runElseBranch = true,
      reason: OpenChangeReason = 'hover',
    ) => {
      const closeDelay = getDelay(
        delayRef.current,
        'close',
        pointerTypeRef.current,
      );
      if (closeDelay && !handlerRef.current) {
        clearTimeoutIfSet(timeoutRef);
        timeoutRef.current = window.setTimeout(
          () => onOpenChange(false, event, reason),
          closeDelay,
        );
      } else if (runElseBranch) {
        clearTimeoutIfSet(timeoutRef);
        onOpenChange(false, event, reason);
      }
    },
    [delayRef, onOpenChange],
  );

  const cleanupMouseMoveHandler = useEffectEvent(() => {
    unbindMouseMoveRef.current();
    handlerRef.current = undefined;
  });

  const clearPointerEvents = useEffectEvent(() => {
    if (performedPointerEventsMutationRef.current) {
      const body = getDocument(elements.floating).body;
      body.style.pointerEvents = '';
      body.removeAttribute(safePolygonIdentifier);
      performedPointerEventsMutationRef.current = false;
    }
  });

  const isClickLikeOpenEvent = useEffectEvent(() => {
    return dataRef.current.openEvent
      ? ['click', 'mousedown'].includes(dataRef.current.openEvent.type)
      : false;
  });

  // Registering the mouse events on the reference directly to bypass React's
  // delegation system. If the cursor was on a disabled element and then entered
  // the reference (no gap), `mouseenter` doesn't fire in the delegation system.
  React.useEffect(() => {
    if (!enabled) return;

    function onReferenceMouseEnter(event: MouseEvent) {
      console.log('onReferenceMouseEnter');
      clearTimeoutIfSet(timeoutRef);
      blockMouseMoveRef.current = false;

      if (
        (mouseOnly && !isMouseLikePointerType(pointerTypeRef.current)) ||
        (getRestMs(restMsRef.current) > 0 &&
          !getDelay(delayRef.current, 'open'))
      ) {
        return;
      }

      const openDelay = getDelay(
        delayRef.current,
        'open',
        pointerTypeRef.current,
      );

      if (openDelay) {
        timeoutRef.current = window.setTimeout(() => {
          if (!openRef.current) {
            onOpenChange(true, event, 'hover');
          }
        }, openDelay);
      } else if (!open) {
        onOpenChange(true, event, 'hover');
      }
    }

    function onReferenceMouseLeave(event: MouseEvent) {
      console.log('onReferenceMouseLeave')
      if (isClickLikeOpenEvent()) {
        clearPointerEvents();
        return;
      }

      unbindMouseMoveRef.current();

      const doc = getDocument(elements.floating);
      clearTimeoutIfSet(restTimeoutRef);
      restTimeoutPendingRef.current = false;

      if (handleCloseRef.current && dataRef.current.floatingContext) {
        // Prevent clearing `onScrollMouseLeave` timeout.
        if (!open) {
          clearTimeoutIfSet(timeoutRef);
        }

        handlerRef.current = handleCloseRef.current({
          ...dataRef.current.floatingContext,
          tree,
          x: event.clientX,
          y: event.clientY,
          onClose() {
            clearPointerEvents();
            cleanupMouseMoveHandler();
            if (!isClickLikeOpenEvent()) {
              closeWithDelay(event, true, 'safe-polygon');
            }
          },
        });

        const handler = handlerRef.current;

        doc.addEventListener('mousemove', handler);
        unbindMouseMoveRef.current = () => {
          doc.removeEventListener('mousemove', handler);
        };

        return;
      }

      // Allow interactivity without `safePolygon` on touch devices. With a
      // pointer, a short close delay is an alternative, so it should work
      // consistently.
      const shouldClose =
        pointerTypeRef.current === 'touch'
          ? !contains(elements.floating, event.relatedTarget as Element | null)
          : true;
      if (shouldClose) {
        closeWithDelay(event);
      }
    }

    // Ensure the floating element closes after scrolling even if the pointer
    // did not move.
    // https://github.com/floating-ui/floating-ui/discussions/1692
    function onScrollMouseLeave(event: MouseEvent) {
      if (isClickLikeOpenEvent()) return;
      if (!dataRef.current.floatingContext) return;

      handleCloseRef.current?.({
        ...dataRef.current.floatingContext,
        tree,
        x: event.clientX,
        y: event.clientY,
        onClose() {
          clearPointerEvents();
          cleanupMouseMoveHandler();
          if (!isClickLikeOpenEvent()) {
            closeWithDelay(event);
          }
        },
      })(event);
    }

    function onFloatingMouseEnter() {
      clearTimeoutIfSet(timeoutRef);
    }

    function onFloatingMouseLeave(event: MouseEvent) {
      if (!isClickLikeOpenEvent()) {
        closeWithDelay(event, false);
      }
    }

    if (isElement(elements.domReference)) {
      const reference = elements.domReference as unknown as HTMLElement;
      const floating = elements.floating;

      if (open) {
        reference.addEventListener('mouseleave', onScrollMouseLeave);
      }

      if (move) {
        reference.addEventListener('mousemove', onReferenceMouseEnter, {
          once: true,
        });
      }

      reference.addEventListener('mouseenter', onReferenceMouseEnter);
      reference.addEventListener('mouseleave', onReferenceMouseLeave);

      if (floating) {
        floating.addEventListener('mouseleave', onScrollMouseLeave);
        floating.addEventListener('mouseenter', onFloatingMouseEnter);
        floating.addEventListener('mouseleave', onFloatingMouseLeave);
      }

      return () => {
        if (open) {
          reference.removeEventListener('mouseleave', onScrollMouseLeave);
        }

        if (move) {
          reference.removeEventListener('mousemove', onReferenceMouseEnter);
        }

        reference.removeEventListener('mouseenter', onReferenceMouseEnter);
        reference.removeEventListener('mouseleave', onReferenceMouseLeave);

        if (floating) {
          floating.removeEventListener('mouseleave', onScrollMouseLeave);
          floating.removeEventListener('mouseenter', onFloatingMouseEnter);
          floating.removeEventListener('mouseleave', onFloatingMouseLeave);
        }
      };
    }
  }, [
    elements,
    enabled,
    context,
    mouseOnly,
    move,
    closeWithDelay,
    cleanupMouseMoveHandler,
    clearPointerEvents,
    onOpenChange,
    open,
    openRef,
    tree,
    delayRef,
    handleCloseRef,
    dataRef,
    isClickLikeOpenEvent,
    restMsRef,
  ]);

  // Block pointer-events of every element other than the reference and floating
  // while the floating element is open and has a `handleClose` handler. Also
  // handles nested floating elements.
  // https://github.com/floating-ui/floating-ui/issues/1722
  useModernLayoutEffect(() => {
    if (!enabled) return;

    if (
      open &&
      handleCloseRef.current?.__options?.blockPointerEvents &&
      isHoverOpen()
    ) {
      performedPointerEventsMutationRef.current = true;
      const floatingEl = elements.floating;

      if (isElement(elements.domReference) && floatingEl) {
        const body = getDocument(elements.floating).body;
        body.setAttribute(safePolygonIdentifier, '');

        const ref = elements.domReference as unknown as
          | HTMLElement
          | SVGSVGElement;

        const parentFloating = tree?.nodesRef.current.find(
          (node) => node.id === parentId,
        )?.context?.elements.floating;

        if (parentFloating) {
          parentFloating.style.pointerEvents = '';
        }

        body.style.pointerEvents = 'none';
        ref.style.pointerEvents = 'auto';
        floatingEl.style.pointerEvents = 'auto';

        return () => {
          body.style.pointerEvents = '';
          ref.style.pointerEvents = '';
          floatingEl.style.pointerEvents = '';
        };
      }
    }
  }, [enabled, open, parentId, elements, tree, handleCloseRef, isHoverOpen]);

  useModernLayoutEffect(() => {
    if (!open) {
      pointerTypeRef.current = undefined;
      restTimeoutPendingRef.current = false;
      cleanupMouseMoveHandler();
      clearPointerEvents();
    }
  }, [open, cleanupMouseMoveHandler, clearPointerEvents]);

  React.useEffect(() => {
    return () => {
      cleanupMouseMoveHandler();
      clearTimeoutIfSet(timeoutRef);
      clearTimeoutIfSet(restTimeoutRef);
      clearPointerEvents();
    };
  }, [
    enabled,
    elements.domReference,
    cleanupMouseMoveHandler,
    clearPointerEvents,
  ]);

  const reference: ElementProps['reference'] = React.useMemo(() => {
    function setPointerRef(event: React.PointerEvent) {
      pointerTypeRef.current = event.pointerType;
    }

    return {
      onPointerDown: setPointerRef,
      onPointerEnter: setPointerRef,
      onMouseMove(event) {
        const {nativeEvent} = event;

        function handleMouseMove() {
          if (!blockMouseMoveRef.current && !openRef.current) {
            onOpenChange(true, nativeEvent, 'hover');
          }
        }

        if (mouseOnly && !isMouseLikePointerType(pointerTypeRef.current)) {
          return;
        }

        if (open || getRestMs(restMsRef.current) === 0) {
          return;
        }

        // Ignore insignificant movements to account for tremors.
        if (
          restTimeoutPendingRef.current &&
          event.movementX ** 2 + event.movementY ** 2 < 2
        ) {
          return;
        }

        clearTimeoutIfSet(restTimeoutRef);

        if (pointerTypeRef.current === 'touch') {
          handleMouseMove();
        } else {
          restTimeoutPendingRef.current = true;
          restTimeoutRef.current = window.setTimeout(
            handleMouseMove,
            getRestMs(restMsRef.current),
          );
        }
      },
    };
  }, [mouseOnly, onOpenChange, open, openRef, restMsRef]);

  return React.useMemo(
    () => (enabled ? {reference} : {}),
    [enabled, reference],
  );
}

// packages/solid/src/hooks/useHover.ts
import {
  Accessor,
  createEffect,
  createMemo,
  mergeProps,
  onCleanup,
} from 'solid-js';
import {access, MaybeAccessor} from '@solid-primitives/utils';
import {isElement} from '@floating-ui/utils/dom';
import {
  useFloatingParentNodeId,
  useUnsafeFloatingTree,
} from '../components/FloatingTree';
import type {
  ElementProps,
  FloatingContext,
  FloatingTreeType,
  OpenChangeReason,
  ReferenceType,
} from '../types';
import {contains, getDocument} from '../utils/element';
import {isMouseLikePointerType} from '../utils/event';
import {createAttribute} from '../utils/createAttribute';
import {clearTimeoutIfSet} from '../utils/clearTimeoutIfSet';
import {destructure} from '../utils/destructure';

const safePolygonIdentifier = createAttribute('safe-polygon');

export interface HandleCloseFn<RT extends ReferenceType = ReferenceType> {
  (
    context: FloatingContext<RT> & {
      onClose: () => void;
      tree?: FloatingTreeType<RT> | null;
      leave?: boolean;
    },
  ): (event: MouseEvent) => void;
  __options: {
    blockPointerEvents: boolean;
  };
}

export function getDelay(
  value: MaybeAccessor<number | Partial<{open: number; close: number}>>,
  prop: 'open' | 'close',
  pointerType?: PointerEvent['pointerType'],
) {
  const valueRef = access(value);
  if (pointerType && !isMouseLikePointerType(pointerType)) {
    return 0;
  }

  if (typeof valueRef === 'number') {
    return valueRef;
  }

  if (typeof value === 'function') {
    const result = value();
    if (typeof result === 'number') {
      return result;
    }
    return result?.[prop];
  }

  return valueRef?.[prop];
}

function getRestMs(value: number | (() => number)) {
  if (typeof value === 'function') {
    return value();
  }
  return value;
}

export interface UseHoverProps<RT extends ReferenceType = ReferenceType> {
  /**
   * Whether the Hook is enabled, including all internal Effects and event
   * handlers.
   * @default true
   */
  enabled?: MaybeAccessor<boolean>;
  /**
   * Accepts an event handler that runs on `mousemove` to control when the
   * floating element closes once the cursor leaves the reference element.
   * @default null
   */
  handleClose?: HandleCloseFn<RT>;
  /**
   * Waits until the user’s cursor is at “rest” over the reference element
   * before changing the `open` state.
   * @default 0
   */
  restMs?: MaybeAccessor<number>;
  /**
   * Waits for the specified time when the event listener runs before changing
   * the `open` state.
   * @default 0
   */
  delay?: MaybeAccessor<number | Partial<{open: number; close: number}>>;
  /**
   * Whether the logic only runs for mouse input, ignoring touch input.
   * Note: due to a bug with Linux Chrome, "pen" inputs are considered "mouse".
   * @default false
   */
  mouseOnly?: MaybeAccessor<boolean>;
  /**
   * Whether moving the cursor over the floating element will open it, without a
   * regular hover event required.
   * @default true
   */
  move?: MaybeAccessor<boolean>;
}

/**
 * Opens the floating element while hovering over the reference element, like
 * CSS `:hover`.
 * @see https://floating-ui.com/docs/useHover
 */
export function useHover<RT extends ReferenceType = ReferenceType>(
  context: Accessor<FloatingContext<RT>>,
  props: UseHoverProps<RT> = {},
): Accessor<ElementProps> {
  const {open, onOpenChange, refs} = context();
  const mergedProps = mergeProps(
    {
      enabled: true,
      delay: 0,
      handleClose: null,
      mouseOnly: false,
      restMs: 0,
      move: true,
    },
    props,
  ) as Required<Omit<UseHoverProps, 'handleClose'>> & {
    handleClose?: HandleCloseFn<RT>;
  };
  const {enabled, mouseOnly, restMs, move, delay} = destructure(mergedProps, {
    normalize: true,
  });

  // eslint-disable-next-line solid/reactivity
  const {handleClose} = mergedProps;
  const handleCloseRef = handleClose;
  const tree = useUnsafeFloatingTree<RT>();
  const parentId = useFloatingParentNodeId();

  let pointerTypeRef: string | undefined;
  let timeoutRef: any;
  let handlerRef: ((event: MouseEvent) => void) | null | undefined;
  let restTimeoutRef: any;
  let blockMouseMoveRef = true;
  let performedPointerEventsMutationRef = false;
  let unbindMouseMoveRef = () => {};

  const isHoverOpen = () => {
    const type = context().dataRef.openEvent?.type;

    return type?.includes('mouse') && type !== 'mousedown';
  };

  // When dismissing before opening, clear the delay timeouts to cancel it
  // from showing.
  function onDismiss() {
    clearTimeout(timeoutRef);
    clearTimeout(restTimeoutRef);
    blockMouseMoveRef = true;
  }
  createEffect(() => {
    if (!enabled()) {
      return context().events.off('dismiss', onDismiss);
    }
    context().events.on('dismiss', onDismiss);
  });
  onCleanup(() => {
    context().events.off('dismiss', onDismiss);
  });

  createEffect(() => {
    if (!enabled() || !handleClose || !open()) {
      return;
    }

    function onLeave(event: MouseEvent) {
      if (isHoverOpen()) {
        onOpenChange(false, event, 'hover');
      }
    }

    const html = getDocument(refs.floating()).documentElement;
    html?.addEventListener('mouseleave', onLeave);
    onCleanup(() => {
      html?.removeEventListener('mouseleave', onLeave);
    });
  });

  const closeWithDelay = (event: Event, runElseBranch = true, reason: OpenChangeReason = 'hover') => {
    const closeDelay = getDelay(delay(), 'close', pointerTypeRef);
    if (closeDelay && !handlerRef) {
      clearTimeout(timeoutRef);

      timeoutRef = setTimeout(() => onOpenChange(false, event, reason), closeDelay);
    } else if (runElseBranch) {
      clearTimeout(timeoutRef);

      onOpenChange(false, event, reason);
    }
  };

  const cleanupMouseMoveHandler = () => {
    unbindMouseMoveRef();
    handlerRef = undefined;
  };

  const clearPointerEvents = () => {    
    if (performedPointerEventsMutationRef) {
      const body = getDocument(refs.floating()).body;
      body.style.pointerEvents = '';
      body.removeAttribute(safePolygonIdentifier);
      performedPointerEventsMutationRef = false;
    }
  };

  function isClickLikeOpenEvent() {
    return context().dataRef.openEvent
      ? ['click', 'mousedown'].includes(
          context()?.dataRef?.openEvent?.type ?? '',
        )
      : false;
  }

  // Registering the mouse events on the reference directly to bypass React's
  // delegation system. If the cursor was on a disabled element and then entered
  // the reference (no gap), `mouseenter` doesn't fire in the delegation system.
  createEffect(() => {
    if (!enabled()) {
      return;
    }    

    function onMouseEnter(event: MouseEvent) {
      clearTimeout(timeoutRef);
      blockMouseMoveRef = false;

      if (
        (mouseOnly() && !isMouseLikePointerType(pointerTypeRef)) ||
        (getRestMs(restMs()) > 0 && getDelay(delay(), 'open') === 0)
      ) {
        return;
      }

      const openDelay = getDelay(delay(), 'open', pointerTypeRef);
      if (openDelay) {
        timeoutRef = setTimeout(() => {
          onOpenChange(true, event, 'hover');
        }, openDelay);
      } else {
        onOpenChange(true, event, 'hover');
      }
    }

    function onMouseLeave(event: MouseEvent) {      
      if (isClickLikeOpenEvent()) {
        clearPointerEvents();
        return;
      }

      unbindMouseMoveRef();

      const doc = getDocument(refs.floating());
      clearTimeout(restTimeoutRef);

      if (handleCloseRef) {
        // Prevent clearing `onScrollMouseLeave` timeout.
        if (!open()) {
          clearTimeout(timeoutRef);
        }

        handlerRef = handleCloseRef({
          ...context(),
          tree: tree?.(),
          x: event.clientX,
          y: event.clientY,
          onClose() {
            clearPointerEvents();
            cleanupMouseMoveHandler();
            // Should the event expose that it was closed by `safePolygon`?
            if (!isClickLikeOpenEvent()) {
              closeWithDelay(event, true, 'safe-polygon');
            }
          },
        });

        const handler = handlerRef;

        doc.addEventListener('mousemove', handler);
        unbindMouseMoveRef = () => {
          doc.removeEventListener('mousemove', handler);
        };

        return;
      }

      // Allow interactivity without `safePolygon` on touch devices. With a
      // pointer, a short close delay is an alternative, so it should work
      // consistently.
      const shouldClose =
        pointerTypeRef === 'touch'
          ? !contains(refs.floating(), event.relatedTarget as Element | null)
          : true;
      if (shouldClose) {
        closeWithDelay(event);
      }
    }

    // Ensure the floating element closes after scrolling even if the pointer
    // did not move.
    // https://github.com/floating-ui/floating-ui/discussions/1692
    function onScrollMouseLeave(event: MouseEvent) {
      if (isClickLikeOpenEvent()) {
        return;
      }

      handleCloseRef?.({
        ...context(),
        tree: tree?.(),
        x: event.clientX,
        y: event.clientY,
        onClose() {
          clearPointerEvents();
          cleanupMouseMoveHandler();

          if (!isClickLikeOpenEvent()) {
            closeWithDelay(event);
          }
        },
      })(event);
    }

    function onFloatingMouseEnter() {
      clearTimeoutIfSet(timeoutRef);
    }

    function onFloatingMouseLeave(event: MouseEvent) {
      if (!isClickLikeOpenEvent()) {
        closeWithDelay(event, false);
      }
    }

    if (isElement(refs.reference())) {
      const ref = refs.reference() as unknown as HTMLElement;
      const floating = refs.floating();

      if (open()) {
        ref.addEventListener('mouseleave', onScrollMouseLeave);
      }

      if (move()) {
        ref.addEventListener('mousemove', onMouseEnter, {once: true});
      }

      ref.addEventListener('mouseenter', (e) => onMouseEnter(e));
      ref.addEventListener('mouseleave', (e) => onMouseLeave(e));

      if (floating) {
        refs.floating()?.addEventListener('mouseleave', onScrollMouseLeave);
        refs.floating()?.addEventListener('mouseenter', onFloatingMouseEnter);
        refs.floating()?.addEventListener('mouseleave', onFloatingMouseLeave);
      }

      onCleanup(() => {
        if (open()) {
          ref.removeEventListener('mouseleave', onScrollMouseLeave);
        }

        if (move()) {
          ref.removeEventListener('mousemove', onMouseEnter);
        }

        ref.removeEventListener('mouseenter', onMouseEnter);
        ref.removeEventListener('mouseleave', onMouseLeave);

        if (floating) {
          refs.floating()?.removeEventListener('mouseleave', onScrollMouseLeave);
          refs.floating()?.addEventListener('mouseenter', onFloatingMouseEnter);
          refs.floating()?.addEventListener('mouseleave', onFloatingMouseLeave);
        }
      });
    }
  });

  // Block pointer-events of every element other than the reference and floating
  // while the floating element is open and has a `handleClose` handler. Also
  // handles nested floating elements.
  // https://github.com/floating-ui/floating-ui/issues/1722
  createEffect(() => {
    if (!enabled()) {
      return;
    }

    if (
      open() &&
      handleCloseRef?.__options.blockPointerEvents &&
      isHoverOpen()
    ) {
      const floating = refs.floating();
      const domReference = refs.reference();

      if (isElement(domReference) && floating) {
        const doc = floating ? getDocument(floating) : null;
        const body = doc ? doc.body : null;
        // Guard against null body/node
        if (!body) return;
        body.setAttribute(safePolygonIdentifier, '');
        performedPointerEventsMutationRef = true;
      
        const ref = domReference as unknown as HTMLElement | SVGSVGElement;

        const parentFloating = tree
          ?.()
          .nodesRef.find((node) => node.id === parentId)
          ?.context?.refs.floating();

        if (parentFloating) {
          parentFloating.style.pointerEvents = '';
        }

        body.style.pointerEvents = 'none';
        ref.style.pointerEvents = 'auto';
        floating.style.pointerEvents = 'auto';

        onCleanup(() => {
          body.style.pointerEvents = '';
          ref.style.pointerEvents = '';
          floating.style.pointerEvents = '';
        });
      }
    }
  });

  createEffect(() => {
    if (!open()) {
      pointerTypeRef = undefined;
      cleanupMouseMoveHandler();
      clearPointerEvents();
    }
  });

  createEffect(() => {
    //subscribe
    refs.reference();
    //end of subscribe
    cleanupMouseMoveHandler();
    clearTimeout(timeoutRef);
    clearTimeout(restTimeoutRef);
    clearPointerEvents();
  });

  function setPointerRef(event: PointerEvent) {
    pointerTypeRef = event.pointerType;
  }

  const userProps = createMemo(() => {
    if (!enabled()) return {};

    return {
      reference: {
        onPointerDown: setPointerRef,
        onPointerEnter: setPointerRef,
        onMouseMove(event: MouseEvent) {
          if (open() || getRestMs(restMs()) === 0) {
            return;
          }
          clearTimeout(restTimeoutRef);
          restTimeoutRef = setTimeout(() => {
            if (!blockMouseMoveRef) {
              onOpenChange(true, event, 'hover');
            }
          }, getRestMs(restMs()));
        },
      },
      floating: {
        onMouseEnter() {
          clearTimeout(timeoutRef);
        },
        onMouseLeave(event: MouseEvent) {
          context().events.emit('dismiss', {
            type: 'mouseLeave',
            data: {
              returnFocus: false,
            },
          });
          closeWithDelay(event, false);
        },
      },
    };
  });
  return userProps;
}
